### ISSUE TITLE
'float' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by MengXinChengXuYuan** [marvis/pytorch-yolo3#4]
Hi, thanks for your great work first
I got this when running the detect as in the readme.md:

```
Loading weights from yolov3.weights... Done!
Traceback (most recent call last):
  File "detect.py", line 114, in <module>
    detect(cfgfile, weightfile, imgfile)
  File "detect.py", line 32, in detect
    boxes = do_detect(m, sized, 0.5, 0.4, use_cuda)
  File "/root/pytorch-yolo3/utils.py", line 337, in do_detect
    list_boxes = model(img)
  File "/opt/conda/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/pytorch-yolo3/darknet.py", line 146, in forward
    boxes = self.models[ind](x)
  File "/opt/conda/lib/python2.7/site-packages/torch/nn/modules/module.py", line 215, in __call__
    var = var[0]
TypeError: 'float' object has no attribute '__getitem__'
```

Seems to be some kind of version problem? 
Any ideas?

**Comment by marvis** [comment]
this code works on python2+pytorch0.3.  Maybe you are using old pytorch version.

**Comment by MengXinChengXuYuan** [comment]
Ok I see, maybe it will be better to specify this in readme, just a little suggestion :P

**Comment by MengXinChengXuYuan** [comment]
torch ver 0.2.0_4 works well
